// Synthetic candidate pool — 40 profiles tuned to span the search space
// Clera cares about (React/TS heavy, varied seniority, SF/Remote/LatAm).
// Names are fabricated; companies & cities are real for realism.

export interface SeedCandidate {
  name: string;
  headline: string;
  summary: string;
  skills: string[];
  seniority: "junior" | "mid" | "senior" | "staff" | "principal";
  yearsExperience: number;
  locations: string[];
  currentCompany: string;
  currentRole: string;
  pastCompanies: string[];
  githubUrl?: string;
  linkedinUrl?: string;
}

export const SEED_CANDIDATES: SeedCandidate[] = [
  {
    name: "Maya Castellanos",
    headline: "Senior full-stack engineer, ex-Ramp, ex-YC W21",
    summary:
      "Senior full-stack engineer based in San Francisco. Led the candidate sourcing tooling at Ramp's recruiting platform team. Built React + TypeScript dashboards on top of Supabase + Prisma, shipped Typesense-powered search across 2M candidate records. Previously co-founded a YC W21 fintech that was acquired. Strong product instincts.",
    skills: ["React", "TypeScript", "Next.js", "Supabase", "Prisma", "Typesense", "tRPC", "Tailwind"],
    seniority: "senior",
    yearsExperience: 7,
    locations: ["San Francisco", "Remote"],
    currentCompany: "Ramp",
    currentRole: "Senior Software Engineer",
    pastCompanies: ["Stride (YC W21)", "Square"],
    githubUrl: "https://github.com/example-maya",
    linkedinUrl: "https://linkedin.com/in/example-maya",
  },
  {
    name: "Diego Restrepo",
    headline: "Full-stack engineer, Medellín, ex-Rappi",
    summary:
      "Full-stack engineer in Medellín, Colombia. 4 years at Rappi building internal recruiting & ops tools with React, TypeScript and Postgres. Familiar with Prisma migrations on multi-tenant Supabase setups. Has experience integrating Typesense for vendor search. Open to US-aligned remote roles and willing to relocate to SF.",
    skills: ["React", "TypeScript", "Node.js", "Postgres", "Prisma", "Supabase", "Typesense", "GraphQL"],
    seniority: "mid",
    yearsExperience: 4,
    locations: ["Medellín", "Remote", "LatAm"],
    currentCompany: "Rappi",
    currentRole: "Software Engineer II",
    pastCompanies: ["Platzi"],
    githubUrl: "https://github.com/example-diego",
  },
  {
    name: "Priya Raman",
    headline: "Staff engineer, agentic systems, ex-Anthropic",
    summary:
      "Staff engineer in San Francisco. Spent 3 years at Anthropic building internal tooling around agent evaluation, tool-use traces, and retrieval pipelines. Strong TypeScript + React on the front-end of evaluation dashboards. Earlier at Stripe on the developer platform team. Especially interested in agentic recruiting and hiring infrastructure.",
    skills: ["TypeScript", "React", "Python", "Agentic Systems", "RAG", "Evaluation", "Postgres", "Next.js"],
    seniority: "staff",
    yearsExperience: 10,
    locations: ["San Francisco"],
    currentCompany: "Anthropic",
    currentRole: "Staff Software Engineer",
    pastCompanies: ["Stripe", "Palantir"],
    linkedinUrl: "https://linkedin.com/in/example-priya",
  },
  {
    name: "Jonas Weber",
    headline: "Senior frontend engineer, Berlin, design-systems",
    summary:
      "Senior frontend engineer in Berlin with 6 years on React + TypeScript design systems. Led the Linear-style command-palette rebuild at his current scaleup. Deep Tailwind / Radix expertise. No backend appetite. Would only consider European or fully-remote roles.",
    skills: ["React", "TypeScript", "Tailwind", "Radix", "Design Systems", "Storybook"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["Berlin", "Remote-EU"],
    currentCompany: "Personio",
    currentRole: "Senior Frontend Engineer",
    pastCompanies: ["Zalando"],
  },
  {
    name: "Aaliyah Brooks",
    headline: "Founding engineer at YC W24 recruiting startup",
    summary:
      "Founding engineer at a YC W24 recruiting-AI startup in San Francisco. Single-handedly built the candidate matching loop on Next.js + Supabase + Typesense + OpenAI function-calling. Ships 5+ PRs/day. Looking to leave because the founders pivoted away from recruiting.",
    skills: ["Next.js", "TypeScript", "Supabase", "Prisma", "Typesense", "OpenAI", "Tailwind", "tRPC"],
    seniority: "senior",
    yearsExperience: 5,
    locations: ["San Francisco"],
    currentCompany: "Stealth (YC W24)",
    currentRole: "Founding Engineer",
    pastCompanies: ["Brex", "Coinbase"],
    githubUrl: "https://github.com/example-aaliyah",
  },
  {
    name: "Tomás Aguilar",
    headline: "Full-stack engineer, Buenos Aires, ex-Mercado Libre",
    summary:
      "Full-stack engineer in Buenos Aires, 5 years at Mercado Libre on the internal hiring platform. Strong on React, TypeScript, Prisma. Built a Typesense-powered job match service for internal mobility. Active in the LatAm hacker-house circuit (Buidl Buenos Aires, House of DAOs).",
    skills: ["React", "TypeScript", "Node.js", "Prisma", "Typesense", "Postgres", "Docker"],
    seniority: "mid",
    yearsExperience: 5,
    locations: ["Buenos Aires", "LatAm", "Remote"],
    currentCompany: "Mercado Libre",
    currentRole: "Senior SDE",
    pastCompanies: ["Globant"],
    githubUrl: "https://github.com/example-tomas",
  },
  {
    name: "Hannah Kim",
    headline: "ML engineer, ex-OpenAI, Python-heavy",
    summary:
      "Machine learning engineer in San Francisco. Spent 3 years at OpenAI on RLHF infra. Mostly Python and PyTorch. Has shipped Next.js dashboards but it's not her main strength. Looking for an ML-leaning role.",
    skills: ["Python", "PyTorch", "RLHF", "CUDA", "Distributed Training"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["San Francisco"],
    currentCompany: "OpenAI",
    currentRole: "Member of Technical Staff",
    pastCompanies: ["Google Brain"],
  },
  {
    name: "Lucas Petrov",
    headline: "Junior full-stack engineer, recent MIT grad",
    summary:
      "Recent MIT CS grad now in NYC. 1 year at a YC startup on a React + TS + Supabase stack. Strong GitHub profile with several agentic side projects (a Cursor-style PR reviewer, an LLM-driven debugger). Hungry, scrappy, willing to relocate to SF or LatAm.",
    skills: ["React", "TypeScript", "Next.js", "Supabase", "Prisma", "OpenAI", "Tailwind"],
    seniority: "junior",
    yearsExperience: 1,
    locations: ["New York", "San Francisco", "Remote"],
    currentCompany: "Mintlify",
    currentRole: "Software Engineer",
    pastCompanies: [],
    githubUrl: "https://github.com/example-lucas",
  },
  {
    name: "Sofia Mendes",
    headline: "Senior full-stack, ex-Stripe, recruiting-tech",
    summary:
      "Senior engineer in San Francisco. 4 years at Stripe on the internal recruiting tooling team; built sourcing pipelines and an LLM-augmented JD parser. Deep React + TypeScript + Postgres background. Has used Typesense at a previous startup. Specifically wants to work on hiring AI.",
    skills: ["React", "TypeScript", "Postgres", "Prisma", "Typesense", "Ruby", "GraphQL"],
    seniority: "senior",
    yearsExperience: 8,
    locations: ["San Francisco"],
    currentCompany: "Stripe",
    currentRole: "Senior Software Engineer",
    pastCompanies: ["Gem (recruiting startup)"],
    linkedinUrl: "https://linkedin.com/in/example-sofia",
  },
  {
    name: "Ravi Iyer",
    headline: "Backend engineer, Bangalore, Go + Postgres",
    summary:
      "Backend engineer in Bangalore. 5 years on payments infra in Go and Postgres. Touched React once and didn't like it. Wants a backend-only role.",
    skills: ["Go", "Postgres", "Kafka", "Kubernetes", "Redis"],
    seniority: "senior",
    yearsExperience: 5,
    locations: ["Bangalore", "Remote-APAC"],
    currentCompany: "Razorpay",
    currentRole: "Senior Backend Engineer",
    pastCompanies: ["Flipkart"],
  },
  {
    name: "Elena Vasquez",
    headline: "Founding engineer, ex-Vercel, LatAm",
    summary:
      "Founding engineer profile, currently in Mexico City. 5 years at Vercel on the dashboard team — deep Next.js, React Server Components, Tailwind. Loves shipping. Open to founding-team roles in SF or extended LatAm stints. Has used Supabase + Prisma on personal projects.",
    skills: ["Next.js", "React", "TypeScript", "Tailwind", "Supabase", "Prisma", "Vercel"],
    seniority: "senior",
    yearsExperience: 7,
    locations: ["Mexico City", "LatAm", "San Francisco", "Remote"],
    currentCompany: "Vercel",
    currentRole: "Senior Software Engineer",
    pastCompanies: ["Wizeline"],
    githubUrl: "https://github.com/example-elena",
  },
  {
    name: "Marcus Holloway",
    headline: "Staff infra engineer, ex-Datadog",
    summary:
      "Staff infra engineer in NYC. Pure platform background: Terraform, Kubernetes, observability. Has no recent product-engineering or React work. Better fit for infra-heavy roles.",
    skills: ["Go", "Kubernetes", "Terraform", "AWS", "Observability"],
    seniority: "staff",
    yearsExperience: 11,
    locations: ["New York"],
    currentCompany: "Datadog",
    currentRole: "Staff Engineer",
    pastCompanies: ["Etsy"],
  },
  {
    name: "Camila Nunes",
    headline: "Mid full-stack, São Paulo, talent-tech",
    summary:
      "Full-stack engineer in São Paulo, 3 years at Gupy (Brazilian recruiting platform). React + TypeScript on the frontend, Node + Postgres on the backend, Typesense for resume search. Recently shipped an LLM resume parser. Wants to relocate to SF.",
    skills: ["React", "TypeScript", "Node.js", "Postgres", "Typesense", "OpenAI", "Tailwind"],
    seniority: "mid",
    yearsExperience: 3,
    locations: ["São Paulo", "LatAm", "Remote", "San Francisco"],
    currentCompany: "Gupy",
    currentRole: "Software Engineer",
    pastCompanies: ["Nubank"],
    githubUrl: "https://github.com/example-camila",
  },
  {
    name: "Henry Osei",
    headline: "Senior backend engineer, Accra, Python/Django",
    summary:
      "Senior backend engineer in Accra, Ghana. Strong Python/Django background. Some React but rusty. Better for backend-leaning roles.",
    skills: ["Python", "Django", "Postgres", "Celery", "Docker"],
    seniority: "senior",
    yearsExperience: 7,
    locations: ["Accra", "Remote"],
    currentCompany: "Chipper Cash",
    currentRole: "Senior Backend Engineer",
    pastCompanies: ["Andela"],
  },
  {
    name: "Olivia Chen",
    headline: "Senior full-stack, ex-Notion",
    summary:
      "Senior full-stack engineer in San Francisco. 5 years at Notion building the recruiting and HR integrations surface. Deep React + TypeScript expertise. Has shipped Prisma + Postgres migrations at scale. Considering early-stage roles.",
    skills: ["React", "TypeScript", "Prisma", "Postgres", "Next.js", "tRPC", "Tailwind"],
    seniority: "senior",
    yearsExperience: 7,
    locations: ["San Francisco"],
    currentCompany: "Notion",
    currentRole: "Senior Software Engineer",
    pastCompanies: ["Airbnb"],
    linkedinUrl: "https://linkedin.com/in/example-olivia",
  },
  {
    name: "Pablo Jiménez",
    headline: "Founding engineer profile, Buenos Aires hacker-house regular",
    summary:
      "Founding engineer in Buenos Aires. Built and sold a small B2B SaaS that used React + Supabase + Typesense. Lives in/around Crecimiento and the Buenos Aires hacker-houses. Now exploring his next thing. Comfortable with daily shipping and 7-day weeks.",
    skills: ["React", "TypeScript", "Supabase", "Prisma", "Typesense", "Next.js", "Stripe"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["Buenos Aires", "LatAm", "Remote"],
    currentCompany: "Independent",
    currentRole: "Founder / Engineer",
    pastCompanies: ["Auth0", "Globant"],
    githubUrl: "https://github.com/example-pablo",
  },
  {
    name: "Naomi Bergstrom",
    headline: "iOS engineer, Stockholm, Swift only",
    summary:
      "iOS engineer in Stockholm. 6 years of Swift + SwiftUI. No web background. Would be a poor fit for a web-stack role.",
    skills: ["Swift", "SwiftUI", "iOS"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["Stockholm", "Remote-EU"],
    currentCompany: "Klarna",
    currentRole: "Senior iOS Engineer",
    pastCompanies: ["Spotify"],
  },
  {
    name: "Anika Sharma",
    headline: "Mid full-stack, SF, ex-Scale AI",
    summary:
      "Full-stack engineer in San Francisco. 3 years at Scale AI on labeling-tool frontends. Strong React + TypeScript. Has used Supabase + Prisma on side projects, including an agentic Cursor-style code reviewer. Wants smaller team and faster iteration.",
    skills: ["React", "TypeScript", "Next.js", "Supabase", "Prisma", "Cursor", "Tailwind"],
    seniority: "mid",
    yearsExperience: 3,
    locations: ["San Francisco"],
    currentCompany: "Scale AI",
    currentRole: "Software Engineer",
    pastCompanies: [],
    githubUrl: "https://github.com/example-anika",
  },
  {
    name: "Felix Brandt",
    headline: "Principal engineer, ex-GitHub",
    summary:
      "Principal engineer in San Francisco. 12 years experience, last 5 at GitHub on the search platform — deep knowledge of inverted indexes, ranking, and code-search. Strong opinions about Typesense vs Elastic. Would only consider lead-architect roles.",
    skills: ["Go", "Rust", "Search", "Typesense", "Elasticsearch", "Postgres"],
    seniority: "principal",
    yearsExperience: 12,
    locations: ["San Francisco"],
    currentCompany: "GitHub",
    currentRole: "Principal Engineer",
    pastCompanies: ["Twitter"],
  },
  {
    name: "Isabela Costa",
    headline: "Junior full-stack, Rio, scrappy GitHub",
    summary:
      "Junior full-stack engineer in Rio. 1.5 years at a small fintech. Very active on GitHub — has built three agentic side projects, including a job-board scraper that ranks postings with Claude. Strong React + TS, picked up Prisma + Supabase recently. Eager to join a hacker-house environment.",
    skills: ["React", "TypeScript", "Next.js", "Supabase", "Prisma", "Tailwind", "Anthropic", "Cursor"],
    seniority: "junior",
    yearsExperience: 2,
    locations: ["Rio de Janeiro", "LatAm", "Remote"],
    currentCompany: "QI Tech",
    currentRole: "Junior Software Engineer",
    pastCompanies: [],
    githubUrl: "https://github.com/example-isabela",
  },
  {
    name: "Daniel Park",
    headline: "Senior full-stack, ex-Linear, design-engineer",
    summary:
      "Senior engineer in San Francisco. 4 years at Linear as a design engineer — pixel-perfect React/TS UIs, custom Tailwind systems, micro-interactions. Has used Prisma + Postgres extensively. Strong design taste.",
    skills: ["React", "TypeScript", "Tailwind", "Prisma", "Postgres", "Framer Motion", "Next.js"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["San Francisco"],
    currentCompany: "Linear",
    currentRole: "Design Engineer",
    pastCompanies: ["Airbnb"],
  },
  {
    name: "Joana Almeida",
    headline: "Full-stack engineer, Lisbon, ex-Remote.com",
    summary:
      "Full-stack engineer in Lisbon. 4 years at Remote.com (the HR-tech unicorn). React + TypeScript + Prisma + Postgres. Has shipped Typesense and OpenSearch internally. Open to relocating, but European-time preferred.",
    skills: ["React", "TypeScript", "Prisma", "Postgres", "Typesense", "Next.js", "Tailwind"],
    seniority: "mid",
    yearsExperience: 4,
    locations: ["Lisbon", "Remote-EU"],
    currentCompany: "Remote.com",
    currentRole: "Software Engineer",
    pastCompanies: ["Talkdesk"],
  },
  {
    name: "Bryan Whitaker",
    headline: "Senior full-stack, ex-Gem, recruiting-AI",
    summary:
      "Senior full-stack engineer in NYC. 4 years at Gem (recruiting AI startup) on candidate-sourcing automation. Knows the recruiting domain cold. React + TypeScript + Supabase. Has shipped Typesense in production. Specifically wants to work on agentic headhunting.",
    skills: ["React", "TypeScript", "Supabase", "Prisma", "Typesense", "Node.js", "OpenAI", "Tailwind"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["New York", "Remote", "San Francisco"],
    currentCompany: "Gem",
    currentRole: "Senior Engineer",
    pastCompanies: ["Greenhouse"],
    linkedinUrl: "https://linkedin.com/in/example-bryan",
    githubUrl: "https://github.com/example-bryan",
  },
  {
    name: "Aroha Williams",
    headline: "Mid full-stack, Auckland, React + TS",
    summary:
      "Full-stack engineer in Auckland. 3 years at Xero on internal tools. Solid React + TypeScript + Postgres. Strong APAC timezone preference.",
    skills: ["React", "TypeScript", "Postgres", "Node.js", "Prisma"],
    seniority: "mid",
    yearsExperience: 3,
    locations: ["Auckland", "Remote-APAC"],
    currentCompany: "Xero",
    currentRole: "Software Engineer",
    pastCompanies: [],
  },
  {
    name: "Mateo Vargas",
    headline: "Founding engineer, Bogotá, agentic AI side projects",
    summary:
      "Founding-engineer mindset in Bogotá. Just left a senior IC role at Bold (Colombian fintech) to look for a US-aligned startup. Strong full-stack React/TS, has shipped Cursor-rules + Supabase + Typesense in production. Currently hacking on an agentic sales-outreach tool.",
    skills: ["React", "TypeScript", "Cursor", "Supabase", "Prisma", "Typesense", "Anthropic", "Next.js"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["Bogotá", "LatAm", "Remote", "San Francisco"],
    currentCompany: "Independent",
    currentRole: "Founding Engineer (self-employed)",
    pastCompanies: ["Bold", "Rappi"],
    githubUrl: "https://github.com/example-mateo",
    linkedinUrl: "https://linkedin.com/in/example-mateo",
  },
  {
    name: "Chloe Bennett",
    headline: "Junior frontend, London, React + TS",
    summary:
      "Junior frontend engineer in London. 1 year at Monzo. Strong React + TypeScript fundamentals. No backend, no Supabase or Prisma yet.",
    skills: ["React", "TypeScript", "Tailwind"],
    seniority: "junior",
    yearsExperience: 1,
    locations: ["London", "Remote-EU"],
    currentCompany: "Monzo",
    currentRole: "Junior Engineer",
    pastCompanies: [],
  },
  {
    name: "Vikram Bose",
    headline: "Senior full-stack, ex-Microsoft, agentic builder",
    summary:
      "Senior engineer in Seattle. 5 years at Microsoft on Copilot infrastructure. Strong React/TypeScript on internal dashboards, deep familiarity with agent tool-use and evaluation. Looking to leave big tech for an agentic startup.",
    skills: ["React", "TypeScript", "Python", "Agentic Systems", "Azure", "Postgres"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["Seattle", "Remote", "San Francisco"],
    currentCompany: "Microsoft",
    currentRole: "Senior SDE",
    pastCompanies: ["Amazon"],
    githubUrl: "https://github.com/example-vikram",
  },
  {
    name: "Renata Salazar",
    headline: "Mid full-stack, Mexico City, ex-Kavak",
    summary:
      "Full-stack engineer in Mexico City. 3 years at Kavak (LatAm unicorn). React + TypeScript + Node + Postgres. Has used Prisma + Supabase on side projects. Active in the CDMX hacker-house scene.",
    skills: ["React", "TypeScript", "Node.js", "Postgres", "Prisma", "Supabase", "Tailwind"],
    seniority: "mid",
    yearsExperience: 4,
    locations: ["Mexico City", "LatAm", "Remote"],
    currentCompany: "Kavak",
    currentRole: "Software Engineer",
    pastCompanies: ["Clip"],
    githubUrl: "https://github.com/example-renata",
  },
  {
    name: "Ethan Sullivan",
    headline: "Senior data engineer, Chicago, SQL-heavy",
    summary:
      "Senior data engineer in Chicago. Snowflake, dbt, Airflow background. Some React but minimal. Not a strong fit for full-stack product work.",
    skills: ["Python", "SQL", "Snowflake", "dbt", "Airflow"],
    seniority: "senior",
    yearsExperience: 8,
    locations: ["Chicago", "Remote"],
    currentCompany: "Grubhub",
    currentRole: "Senior Data Engineer",
    pastCompanies: ["Cars.com"],
  },
  {
    name: "Layla Hassan",
    headline: "Mid full-stack, Dubai, ex-Careem",
    summary:
      "Full-stack engineer in Dubai. 3 years at Careem on internal tooling. React + TypeScript + Node + Postgres. Has explored Prisma + Supabase on side projects.",
    skills: ["React", "TypeScript", "Node.js", "Postgres", "Prisma"],
    seniority: "mid",
    yearsExperience: 4,
    locations: ["Dubai", "Remote"],
    currentCompany: "Careem",
    currentRole: "Software Engineer",
    pastCompanies: [],
  },
  {
    name: "Sebastián Rojas",
    headline: "Junior full-stack, Santiago, scrappy",
    summary:
      "Junior full-stack engineer in Santiago. Self-taught. 1.5 years at a Chilean fintech. Strong GitHub presence with several React + TS + Supabase projects, including a Typesense-powered candidate-search prototype he built for fun.",
    skills: ["React", "TypeScript", "Supabase", "Typesense", "Next.js", "Tailwind"],
    seniority: "junior",
    yearsExperience: 2,
    locations: ["Santiago", "LatAm", "Remote"],
    currentCompany: "Fintual",
    currentRole: "Junior Engineer",
    pastCompanies: [],
    githubUrl: "https://github.com/example-sebastian",
  },
  {
    name: "Jordan Reeves",
    headline: "Staff full-stack, ex-Brex, recruiting infrastructure",
    summary:
      "Staff engineer in San Francisco. 6 years at Brex, last 2 leading the people-tech / recruiting tooling team. Architected the Typesense + Postgres + Prisma sourcing pipeline that recruiters use today. Deep React + TypeScript. Specifically interested in agentic recruiting.",
    skills: ["React", "TypeScript", "Next.js", "Prisma", "Postgres", "Typesense", "Supabase", "OpenAI"],
    seniority: "staff",
    yearsExperience: 9,
    locations: ["San Francisco"],
    currentCompany: "Brex",
    currentRole: "Staff Engineer",
    pastCompanies: ["Plaid"],
    linkedinUrl: "https://linkedin.com/in/example-jordan",
  },
  {
    name: "Mei Tanaka",
    headline: "Senior frontend, Tokyo, React/TS",
    summary:
      "Senior frontend engineer in Tokyo. 6 years on React + TypeScript. Strong design eye. Would only consider APAC-friendly remote work.",
    skills: ["React", "TypeScript", "Next.js", "Tailwind", "Storybook"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["Tokyo", "Remote-APAC"],
    currentCompany: "Mercari",
    currentRole: "Senior Frontend Engineer",
    pastCompanies: ["Rakuten"],
  },
  {
    name: "Owen Carter",
    headline: "Founding engineer at YC W23 dev-tools startup",
    summary:
      "Founding engineer in San Francisco at a YC W23 dev-tools startup. Single-handedly built the React + TS + Supabase + Prisma app, ships 5+ PRs/day. Has used Typesense for log search. Burned out on dev tools and curious about recruiting AI.",
    skills: ["React", "TypeScript", "Supabase", "Prisma", "Typesense", "Next.js", "Cursor", "Tailwind"],
    seniority: "senior",
    yearsExperience: 5,
    locations: ["San Francisco"],
    currentCompany: "Stealth (YC W23)",
    currentRole: "Founding Engineer",
    pastCompanies: ["Snowflake"],
    githubUrl: "https://github.com/example-owen",
  },
  {
    name: "Zara Khan",
    headline: "Senior full-stack, Lahore, remote-only",
    summary:
      "Senior full-stack engineer in Lahore. 6 years on React + TypeScript + Node + Postgres. Has used Prisma + Supabase. Cannot relocate. Available APAC-friendly remote only.",
    skills: ["React", "TypeScript", "Node.js", "Prisma", "Postgres", "Supabase"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["Lahore", "Remote-APAC"],
    currentCompany: "Bazaar Technologies",
    currentRole: "Senior Engineer",
    pastCompanies: [],
  },
  {
    name: "Adam Lindqvist",
    headline: "Mid full-stack, NYC, React/TS",
    summary:
      "Full-stack engineer in NYC. 3 years at a series B fintech. Solid React + TypeScript + Postgres. Some Prisma but no Supabase or Typesense yet. Eager to learn.",
    skills: ["React", "TypeScript", "Postgres", "Prisma", "Node.js"],
    seniority: "mid",
    yearsExperience: 3,
    locations: ["New York", "Remote"],
    currentCompany: "Alloy",
    currentRole: "Software Engineer",
    pastCompanies: [],
  },
  {
    name: "Yuki Sato",
    headline: "Senior engineer, Toronto, ex-Shopify",
    summary:
      "Senior full-stack engineer in Toronto. 5 years at Shopify on Hatch (internal merchant-tools platform). React + TypeScript + Ruby on Rails + Postgres. Has shipped search using Typesense for product catalogs.",
    skills: ["React", "TypeScript", "Ruby", "Rails", "Postgres", "Typesense"],
    seniority: "senior",
    yearsExperience: 6,
    locations: ["Toronto", "Remote", "San Francisco"],
    currentCompany: "Shopify",
    currentRole: "Senior Engineer",
    pastCompanies: ["RBC"],
  },
  {
    name: "Gabriela Ortiz",
    headline: "Mid full-stack, Lima, ex-Yape",
    summary:
      "Full-stack engineer in Lima. 3 years at Yape (Peruvian fintech). React + TypeScript + Node + Postgres. Has used Prisma + Supabase on personal projects. Active in LatAm hacker-house circuits.",
    skills: ["React", "TypeScript", "Node.js", "Postgres", "Prisma", "Supabase"],
    seniority: "mid",
    yearsExperience: 3,
    locations: ["Lima", "LatAm", "Remote"],
    currentCompany: "Yape",
    currentRole: "Software Engineer",
    pastCompanies: [],
    githubUrl: "https://github.com/example-gabriela",
  },
  {
    name: "Theo Andersen",
    headline: "Mid full-stack, Copenhagen, scrappy",
    summary:
      "Full-stack engineer in Copenhagen. 3 years at a small B2B SaaS. React + TypeScript + Prisma + Supabase. Has shipped a Typesense search index. EU-only.",
    skills: ["React", "TypeScript", "Prisma", "Supabase", "Typesense", "Next.js"],
    seniority: "mid",
    yearsExperience: 3,
    locations: ["Copenhagen", "Remote-EU"],
    currentCompany: "Pleo",
    currentRole: "Software Engineer",
    pastCompanies: [],
  },
  {
    name: "Riya Mehta",
    headline: "Senior full-stack, SF, ex-Greenhouse, recruiting domain",
    summary:
      "Senior engineer in San Francisco. 5 years at Greenhouse (recruiting platform). Deep recruiting domain knowledge. React + TypeScript + Postgres + Prisma. Has shipped Typesense and OpenSearch in production. Curious about agentic outreach.",
    skills: ["React", "TypeScript", "Prisma", "Postgres", "Typesense", "Next.js", "Supabase"],
    seniority: "senior",
    yearsExperience: 7,
    locations: ["San Francisco"],
    currentCompany: "Greenhouse",
    currentRole: "Senior Engineer",
    pastCompanies: ["Lever"],
    linkedinUrl: "https://linkedin.com/in/example-riya",
  },
];
